import styled from 'styled-components'

export const Header = styled.div `
width: 100vw;
height: 15vh;
background-color: black;
opacity: 1;
display: flex;
justify-content: space-between;
align-content: center;
color:  #EAEAEA;

& img{
    width: 180px;
    height: 80px;
    margin-top: auto;
    margin-bottom: auto;
    margin-left: 5% ;
}img:hover{
    cursor: pointer;
}
& section{
display: flex;
line-break: auto;
width: 40vw;
margin-top: 20px;
}
& input{
    width: 500px;
    height: 8vh;
    background-color: #f4c6d4;
}input:focus{
    background-color: #EAEAEA;
}
& p{
    margin: auto;
}

`
export const HeaderButton = styled.button`
margin: 5%;
    width: 120px;
    height: 40px;
    color: #ca315f;
    background-color: lightgray;
    font-weight: bolder;
    border-radius: 50px;
    margin-top: auto;
    margin-bottom: auto;
    align-content: center;
    align-items: center;
    display: flex;
    justify-content: space-around;
    padding-inline: 20px;
   
:hover{
    cursor: pointer;
    color: lightgrey;
    background-color: #ca315f;
}
& img{
    height: 18px;
    width: 18px;
   
}

`


export const Main = styled.div`
font-size: x-large;
margin-bottom: 0px;;
overflow: hidden;

height: 85vh;

& h1{
    z-index: 0;
    position: absolute;

    color: #DA094A;
    left: 0; 
    right: 0; 
    top: 200px;
    bottom: 0;
    margin: auto;

    font-style: italic;
    line-break:auto;
    width: 600px;
    text-align: center;
}h1:hover{
    cursor: pointer;
}
& img{
    z-index: 0;
    position: absolute;
    height: 200px;
    width: auto;
    left: 0; 
    right: 0; 
    top: 280px;
    bottom: 0;
    margin: auto;
    filter: grayscale(100%);
}img:hover{
    cursor: pointer;

    /* ----------------------------------------------
 * Generated by Animista on 2022-7-15 12:56:45
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
    
    -webkit-animation: slide-top 2s linear both;
	        animation: slide-top 2s linear both;
            @-webkit-keyframes slide-top {
  0% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
  }
  100% {
    -webkit-transform: translateY(-400px);
            transform: translateY(-400px);
  }
}
@keyframes slide-top {
  0% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
  }
  100% {
    -webkit-transform: translateY(-400px);
            transform: translateY(-400px);
  }
}
}

& video{
  position: relative;
  right: 0;
  bottom: 0;
  width: 100vw;
  height: 85vh;
  object-fit: cover;
  z-index: -1;
  margin-bottom:0px;


}
`